# Generated by Django 3.1 on 2026-01-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ci',
            fields=[
                ('codci', models.CharField(blank=True, db_column='Codci', help_text='Nome do circuito integrado', max_length=15, primary_key=True, serialize=False)),
                ('semana', models.IntegerField(blank=True, db_column='Semana', help_text='Semana que apareceu pela primeira vez', null=True)),
                ('sobre', models.CharField(blank=True, db_column='Sobre', help_text='Descrição do circuito integrado', max_length=75, null=True)),
            ],
            options={
                'db_table': 'ci',
                'ordering': ['semana'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiComent',
            fields=[
                ('codci_coment', models.AutoField(db_column='Codci_coment', primary_key=True, serialize=False)),
                ('obs', models.CharField(blank=True, db_column='Obs', help_text='Observação', max_length=75, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
            ],
            options={
                'db_table': 'ci_coment',
                'ordering': ['ci', 'coment'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('codcoment', models.AutoField(db_column='Codcoment', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', help_text='De maneira geral, do que trata o comentário?', max_length=255, null=True)),
                ('detalhe', models.CharField(blank=True, db_column='Detalhe', help_text='Descreva detalhes ...', max_length=255, null=True)),
            ],
            options={
                'db_table': 'coment',
                'ordering': ['assunto', 'detalhe'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('codcomp', models.CharField(blank=True, db_column='Codcomp', help_text='Nome do componente', max_length=15, primary_key=True, serialize=False)),
                ('sobre', models.CharField(blank=True, db_column='Sobre', help_text='Descrição do componente', max_length=75, null=True)),
            ],
            options={
                'db_table': 'comp',
                'ordering': ['codcomp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompComent',
            fields=[
                ('codcomp_coment', models.AutoField(db_column='Codcomp_coment', primary_key=True, serialize=False)),
                ('obs', models.CharField(blank=True, db_column='Obs', help_text='Observação', max_length=75, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
            ],
            options={
                'db_table': 'comp_coment',
                'ordering': ['comp', 'coment'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codtema', models.AutoField(db_column='Codtema', primary_key=True, serialize=False)),
                ('semana', models.SmallIntegerField(blank=True, db_column='Semana', null=True)),
                ('ordem', models.SmallIntegerField(blank=True, db_column='Ordem', null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=15, null=True)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=255, null=True)),
                ('pagina', models.IntegerField(blank=True, db_column='Pagina', null=True)),
                ('status', models.BooleanField(db_column='Status', default=False, null=True)),
            ],
            options={
                'db_table': 'tema',
                'ordering': ['semana', 'ordem'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemaComent',
            fields=[
                ('codtema_coment', models.AutoField(db_column='Codtema_coment', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
            ],
            options={
                'db_table': 'tema_coment',
                'ordering': ['tema', 'coment'],
                'managed': False,
            },
        ),
    ]
