# Generated by Django 3.1 on 2026-01-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ci',
            options={'ordering': ['semana']},
        ),
        migrations.AlterModelOptions(
            name='cicoment',
            options={'ordering': ['ci', 'coment']},
        ),
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['assunto', 'detalhe']},
        ),
        migrations.AlterModelOptions(
            name='comp',
            options={'ordering': ['codcomp']},
        ),
        migrations.AlterModelOptions(
            name='compcoment',
            options={'ordering': ['comp', 'coment']},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['semana', 'ordem']},
        ),
        migrations.AlterModelOptions(
            name='temacoment',
            options={'ordering': ['tema', 'coment']},
        ),
    ]
