# Generated by Django 3.1 on 2026-02-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0002_auto_20260203_2201'),
    ]

    operations = [

        migrations.AlterField(
            model_name='compcoment',
            name='obs',
            field=models.CharField(
                db_column='obs',
                max_length=275,
                blank=True,
                null=True,
                help_text='Observação, pode ser um link'
            ),
        ),
        migrations.AlterField(
            model_name='cicoment',
            name='obs',
            field=models.CharField(
                db_column='obs',
                max_length=275,
                blank=True,
                null=True,
                help_text='Observação, pode ser um link'
            ),
        ),





    ]
