# Generated by Django 3.1 on 2026-02-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0003_alter_obs_size'),
        ('eletronLab', '0002_auto_20260131_0045'),
    ]

    operations = [
    ]
