# Generated by Django 3.1 on 2026-02-18 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0005_state_sync_20260217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentInfo',
            fields=[
                ('codinfo', models.AutoField(db_column='Codinfo', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', help_text='Título curto (bom para renderizar links).', max_length=150, null=True)),
                ('info', models.TextField(db_column='Info', help_text='Texto longo ou URL.')),
                ('coment', models.ForeignKey(db_column='Coment', on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='eletronLab.coment')),
            ],
            options={
                'db_table': 'coment_info',
                'ordering': ['codinfo'],
            },
        ),
    ]
