# Generated by Django 3.1 on 2026-02-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0006_comentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='status_txt',
            field=models.CharField(choices=[('revisado', 'Revisado'), ('estudado', 'Estudado'), ('nenhum', 'Nenhum')], db_column='StatusTxt', db_index=True, default='nenhum', help_text='Status do tema (texto)', max_length=10),
        ),
    ]
