# Generated by Django 3.1 on 2026-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0008_tema_status_bool_para_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='status_txt',
        ),
        migrations.AlterField(
            model_name='tema',
            name='status',
            field=models.CharField(choices=[('revisado', 'Revisado'), ('estudado', 'Estudado'), ('nenhum', 'Nenhum')], db_column='Status', db_index=True, default='nenhum', help_text='Status do tema (texto)', max_length=10),
        ),
    ]
