# Generated by Django 3.1 on 2026-02-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0009_auto_20260222_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('codinfo', models.AutoField(db_column='Codinfo', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=150, null=True)),
                ('sobre', models.CharField(blank=True, db_column='Sobre', max_length=255, null=True)),
            ],
            options={
                'db_table': 'info',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='coment',
            name='obs',
            field=models.CharField(blank=True, db_column='Obs', help_text='Campo auxiliar (ex.: URL quando assunto="link").', max_length=275, null=True),
        ),
        migrations.CreateModel(
            name='TemaTema',
            fields=[
                ('codtema_tema', models.AutoField(db_column='Codtema_tema', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
                ('tema', models.ForeignKey(blank=True, db_column='Tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacoes_origem', to='eletronLab.tema')),
                ('tema_rel', models.ForeignKey(blank=True, db_column='Tema_rel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relacoes_destino', to='eletronLab.tema')),
            ],
            options={
                'db_table': 'tema_tema',
                'ordering': ['tema', 'tema_rel'],
                'unique_together': {('tema', 'tema_rel')},
            },
        ),
        migrations.CreateModel(
            name='TemaInfo',
            fields=[
                ('codtema_info', models.AutoField(db_column='Codtema_info', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
                ('info', models.ForeignKey(blank=True, db_column='Info', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.info')),
                ('tema', models.ForeignKey(blank=True, db_column='Tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.tema')),
            ],
            options={
                'db_table': 'tema_info',
                'ordering': ['tema', 'info'],
                'unique_together': {('tema', 'info')},
            },
        ),
        migrations.CreateModel(
            name='TemaComp',
            fields=[
                ('codtema_comp', models.AutoField(db_column='Codtema_comp', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
                ('comp', models.ForeignKey(blank=True, db_column='Comp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.comp')),
                ('tema', models.ForeignKey(blank=True, db_column='Tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.tema')),
            ],
            options={
                'db_table': 'tema_comp',
                'ordering': ['tema', 'comp'],
                'unique_together': {('tema', 'comp')},
            },
        ),
        migrations.CreateModel(
            name='TemaCi',
            fields=[
                ('codtema_ci', models.AutoField(db_column='Codtema_ci', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
                ('ci', models.ForeignKey(blank=True, db_column='Ci', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.ci')),
                ('tema', models.ForeignKey(blank=True, db_column='Tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.tema')),
            ],
            options={
                'db_table': 'tema_ci',
                'ordering': ['tema', 'ci'],
                'unique_together': {('tema', 'ci')},
            },
        ),
    ]
