# Generated by Django 3.1 on 2026-02-25 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0012_popula_relacoes_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoComent',
            fields=[
                ('codinfo_coment', models.AutoField(db_column='Codinfo_coment', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='Data', null=True)),
                ('coment', models.ForeignKey(blank=True, db_column='Coment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.coment')),
                ('info', models.ForeignKey(blank=True, db_column='Info', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eletronLab.info')),
            ],
            options={
                'db_table': 'info_coment',
                'ordering': ['info', 'coment'],
                'unique_together': {('info', 'coment')},
            },
        ),
    ]
