# Generated by Django 3.1 on 2026-02-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0014_popula_info_e_infocoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='obs',
            field=models.TextField(blank=True, db_column='Obs', help_text='Observação adicional (link ou texto livre).', null=True),
        ),
    ]
