# Generated by Django 3.1 on 2026-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0016_popula_infocoment_via_comentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ci',
            name='coment',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='coment',
        ),
    ]
