# Generated by Django 3.1 on 2026-03-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0017_auto_20260301_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coment',
            unique_together=set(),
        ),
    ]
