# Generated by Django 3.1 on 2026-03-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0018_auto_20260301_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicoment',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='compcoment',
            name='obs',
        ),
    ]
