# Generated by Django 3.1 on 2026-03-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eletronLab', '0019_auto_20260301_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentInfo',
        ),
    ]
