"""
Django settings for novavisio project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

##-----------------------------IMPORTS------------------------------------------
from pathlib import Path

import os

# Heroku: Update database configuration from $DATABASE_URL.
#import dj_database_url


##-----------------------------GLOBALS------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '6-gth!ei78h8&93+wxsm(priow%r%e^1+v^71z9upn)oxpr7)f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #True False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'gpsgeo.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eletronLab.apps.EletronLabConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'novavisio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'novavisio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
#database local xampp em C:\xampp\mysql\data
##DATABASES = {
##    "default": {
##        "ENGINE": "django.db.backends.mysql",
##        "NAME": "bd_eletronlab",
##        "USER": "root",
##        "PASSWORD": "",
##        "HOST": "127.0.0.1",
##        "PORT": "3306",
##        "OPTIONS": {"charset": "utf8mb4"},
##    }
##}

#database uol host
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "bd_eletronlab",
        "USER": "eletronlab",
        "PASSWORD": "lab1@Eletron",
        "HOST": "bd-eletronlab.mysql.uhserver.com",
        "PORT": "3306",
        "OPTIONS": {"charset": "utf8mb4"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django_project/settings.py
LOGIN_REDIRECT_URL = "home_eLab"
LOGOUT_REDIRECT_URL = "home_eLab"  # new
LOGIN_URL = "/accounts/login/"

SESSION_COOKIE_SECURE = False

CSRF_COOKIE_SECURE = False

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'eletronLab' / 'static',
]

# opcional em dev, mas pode manter
STATIC_ROOT = BASE_DIR / 'staticfiles'


# SECURITY WARNING: check --deploy
SECURE_SSL_REDIRECT = False

# SECURITY WARNING: check --deploy
SECURE_HSTS_SECONDS = 0
